# coding: utf-8
#
# Cookbook Name:: btsync
# Recipe:: default
#
# Copyright 2014, Kenji Akiyama
#
# All rights reserved - Do Not Redistribute
#

include_recipe "apt"

apt_repository 'btsync' do
  uri 'http://ppa.launchpad.net/tuxpoldo/btsync/ubuntu'
  distribution 'trusty'
  components   ['main']
  keyserver    'keyserver.ubuntu.com'
  key          'D294A752'
end

directory node['btsync']['webui']['directory_root'] do
  owner node['btsync']['owner']
  group node['btsync']['group']
  mode '0775'
  recursive true
end

log "installation message" do
  action :nothing
  level :info
  message <<EOS
Default instance automatically created by debconf

DO NOT EDIT THIS FILE MANUALLY - SERIOUSLY!!!

THIS FILE WILL BE OVERWRITTEN AT EVERY UPDATE
OR RECONFIGURATION SO DO NOT EVEN TRY IT

USE dpkg-reconfigure btsync INSTEAD TO MODIFY
THE CONFIGURATION

DAEMON_UID=btsync
DAEMON_GID=btsync
EOS
end

package 'btsync' do
  notifies :run, resources(:log => 'installation message')
end

template '/etc/btsync/debconf-default.conf' do
  source 'default.erb'
  owner node['btsync']['owner']
  group node['btsync']['group']
  mode '0400'
  notifies :run, "execute[reload-setting]", :immediately
end

execute 'reload-setting' do
  command "service btsync force-reload"
  action :nothing
end
